---
extends: "eslint:recommended"
rules:
  comma-dangle: [2, always-multiline]
  quotes: [2, single]
  no-unused-vars: [2, {vars: all, args: none}]
  no-console: [0]

env:
  es6: true
  node: true
  amd: true

